---
- name: Настройка eBGP на роутере Juniper
  hosts: juniper
  connection: local
  gather_facts: no

  tasks:
    - name: BGP as
      ansible.netcommon.cli_config:
        config: "set protocols bgp local-as 65333"

    - name: Отправка команды настройки OSPF для ge-0/0/7
      ansible.netcommon.cli_config:
        config: "set protocols ospf area 0.0.0.100 interface ge-0/0/7"
