---
- name: Настройка eBGP на роутере Juniper
  hosts: juniper
  connection: local
  gather_facts: no

  tasks:
    - name: BGP as
      ansible.netcommon.cli_config:
        config: "set protocols bgp local-as 65333"

    - name: Тут определяю тип группы bgp
      ansible.netcommon.cli_config:
        config:  "set protocols bgp group eBGP type external"

    - name: Тут задаю адрес пира и свой
      ansible.netcommon.cli_config:
        config:  "set protocols bgp group eBGP neighbor 10.10.0.2 local-address 10.10.0.1"

    - name: Здесь задаётся ас для пира
      ansible.netcommon.cli_config:
        config:  "set protocols bgp group eBGP neighbor 10.10.0.2 peer-as 65010"
