---
- name: Настройка ospf на роутере Juniper
  hosts: juniper1
  connection: local
  gather_facts: no

  tasks:
    - name: Gathering interfaces
      ansible.netcommon.cli_config:
        config: "set interfaces interface-range RoInt member-range ge-0/0/0 to ge-0/0/3"

    - name: Setting up ospf to phys
      ansible.netcommon.cli_config:
        config: "set protocols ospf area 0.0.0.0 interface RoInt"
        
    - name: Setting up ospf to lo0
      ansible.netcommon.cli_config:
        config: "set protocols ospf area 0.0.0.0 interface lo0"
